
# Sgluon 350 

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon350_alladded_STD_END_SELECTION_Cat0_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon350_alladded_STD_END_SELECTION_Cat0_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon350_alladded_STD_END_SELECTION_Cat1_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon350_alladded_STD_END_SELECTION_Cat1_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon350_alladded_STD_END_SELECTION_Cat2_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon350_alladded_STD_END_SELECTION_Cat2_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon350_alladded_STD_END_SELECTION_Cat3_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon350_alladded_STD_END_SELECTION_Cat3_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon350_alladded_STD_END_SELECTION_Cat4_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon350_alladded_STD_END_SELECTION_Cat4_alladded_Yield_WITHDATASIMOV.dat

# Sgluon 400 

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon400_alladded_STD_END_SELECTION_Cat0_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon400_alladded_STD_END_SELECTION_Cat0_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon400_alladded_STD_END_SELECTION_Cat1_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon400_alladded_STD_END_SELECTION_Cat1_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon400_alladded_STD_END_SELECTION_Cat2_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon400_alladded_STD_END_SELECTION_Cat2_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon400_alladded_STD_END_SELECTION_Cat3_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon400_alladded_STD_END_SELECTION_Cat3_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon400_alladded_STD_END_SELECTION_Cat4_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon400_alladded_STD_END_SELECTION_Cat4_alladded_Yield_WITHDATASIMOV.dat

# Sgluon 500 

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon500_alladded_STD_END_SELECTION_Cat0_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon500_alladded_STD_END_SELECTION_Cat0_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon500_alladded_STD_END_SELECTION_Cat1_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon500_alladded_STD_END_SELECTION_Cat1_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon500_alladded_STD_END_SELECTION_Cat2_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon500_alladded_STD_END_SELECTION_Cat2_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon500_alladded_STD_END_SELECTION_Cat3_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon500_alladded_STD_END_SELECTION_Cat3_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon500_alladded_STD_END_SELECTION_Cat4_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon500_alladded_STD_END_SELECTION_Cat4_alladded_Yield_WITHDATASIMOV.dat

# Sgluon 600 

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon600_alladded_STD_END_SELECTION_Cat0_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon600_alladded_STD_END_SELECTION_Cat0_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon600_alladded_STD_END_SELECTION_Cat1_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon600_alladded_STD_END_SELECTION_Cat1_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon600_alladded_STD_END_SELECTION_Cat2_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon600_alladded_STD_END_SELECTION_Cat2_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon600_alladded_STD_END_SELECTION_Cat3_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon600_alladded_STD_END_SELECTION_Cat3_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon600_alladded_STD_END_SELECTION_Cat4_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon600_alladded_STD_END_SELECTION_Cat4_alladded_Yield_WITHDATASIMOV.dat

# Sgluon 800 

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon800_alladded_STD_END_SELECTION_Cat0_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon800_alladded_STD_END_SELECTION_Cat0_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon800_alladded_STD_END_SELECTION_Cat1_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon800_alladded_STD_END_SELECTION_Cat1_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon800_alladded_STD_END_SELECTION_Cat2_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon800_alladded_STD_END_SELECTION_Cat2_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon800_alladded_STD_END_SELECTION_Cat3_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon800_alladded_STD_END_SELECTION_Cat3_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon800_alladded_STD_END_SELECTION_Cat4_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon800_alladded_STD_END_SELECTION_Cat4_alladded_Yield_WITHDATASIMOV.dat

# Sgluon 1000 

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon1000_alladded_STD_END_SELECTION_Cat0_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon1000_alladded_STD_END_SELECTION_Cat0_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon1000_alladded_STD_END_SELECTION_Cat1_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon1000_alladded_STD_END_SELECTION_Cat1_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon1000_alladded_STD_END_SELECTION_Cat2_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon1000_alladded_STD_END_SELECTION_Cat2_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon1000_alladded_STD_END_SELECTION_Cat3_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon1000_alladded_STD_END_SELECTION_Cat3_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon1000_alladded_STD_END_SELECTION_Cat4_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon1000_alladded_STD_END_SELECTION_Cat4_alladded_Yield_WITHDATASIMOV.dat

# Sgluon 1250 

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon1250_alladded_STD_END_SELECTION_Cat0_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon1250_alladded_STD_END_SELECTION_Cat0_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon1250_alladded_STD_END_SELECTION_Cat1_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon1250_alladded_STD_END_SELECTION_Cat1_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon1250_alladded_STD_END_SELECTION_Cat2_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon1250_alladded_STD_END_SELECTION_Cat2_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon1250_alladded_STD_END_SELECTION_Cat3_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon1250_alladded_STD_END_SELECTION_Cat3_alladded_Yield_WITHDATASIMOV.dat

./AddYieldDataAsimov.awk Files_10April2014/DAT/CH_Sgluon1250_alladded_STD_END_SELECTION_Cat4_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon1250_alladded_STD_END_SELECTION_Cat4_alladded_Yield_WITHDATASIMOV.dat
