
# Sgluon 350 

./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon350_alladded_STD_END_SELECTION_Cat0_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon350_alladded_STD_END_SELECTION_Cat0_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon350_alladded_STD_END_SELECTION_Cat1_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon350_alladded_STD_END_SELECTION_Cat1_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon350_alladded_STD_END_SELECTION_Cat2_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon350_alladded_STD_END_SELECTION_Cat2_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon350_alladded_STD_END_SELECTION_Cat3_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon350_alladded_STD_END_SELECTION_Cat3_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon350_alladded_STD_END_SELECTION_Cat4_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon350_alladded_STD_END_SELECTION_Cat4_alladded_Yield_NOUNCERTBUTSTAT.dat

# Sgluon 400 

./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon400_alladded_STD_END_SELECTION_Cat0_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon400_alladded_STD_END_SELECTION_Cat0_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon400_alladded_STD_END_SELECTION_Cat1_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon400_alladded_STD_END_SELECTION_Cat1_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon400_alladded_STD_END_SELECTION_Cat2_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon400_alladded_STD_END_SELECTION_Cat2_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon400_alladded_STD_END_SELECTION_Cat3_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon400_alladded_STD_END_SELECTION_Cat3_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon400_alladded_STD_END_SELECTION_Cat4_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon400_alladded_STD_END_SELECTION_Cat4_alladded_Yield_NOUNCERTBUTSTAT.dat

# Sgluon 500 

./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon500_alladded_STD_END_SELECTION_Cat0_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon500_alladded_STD_END_SELECTION_Cat0_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon500_alladded_STD_END_SELECTION_Cat1_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon500_alladded_STD_END_SELECTION_Cat1_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon500_alladded_STD_END_SELECTION_Cat2_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon500_alladded_STD_END_SELECTION_Cat2_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon500_alladded_STD_END_SELECTION_Cat3_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon500_alladded_STD_END_SELECTION_Cat3_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon500_alladded_STD_END_SELECTION_Cat4_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon500_alladded_STD_END_SELECTION_Cat4_alladded_Yield_NOUNCERTBUTSTAT.dat

# Sgluon 600 

./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon600_alladded_STD_END_SELECTION_Cat0_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon600_alladded_STD_END_SELECTION_Cat0_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon600_alladded_STD_END_SELECTION_Cat1_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon600_alladded_STD_END_SELECTION_Cat1_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon600_alladded_STD_END_SELECTION_Cat2_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon600_alladded_STD_END_SELECTION_Cat2_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon600_alladded_STD_END_SELECTION_Cat3_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon600_alladded_STD_END_SELECTION_Cat3_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon600_alladded_STD_END_SELECTION_Cat4_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon600_alladded_STD_END_SELECTION_Cat4_alladded_Yield_NOUNCERTBUTSTAT.dat

# Sgluon 800 

./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon800_alladded_STD_END_SELECTION_Cat0_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon800_alladded_STD_END_SELECTION_Cat0_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon800_alladded_STD_END_SELECTION_Cat1_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon800_alladded_STD_END_SELECTION_Cat1_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon800_alladded_STD_END_SELECTION_Cat2_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon800_alladded_STD_END_SELECTION_Cat2_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon800_alladded_STD_END_SELECTION_Cat3_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon800_alladded_STD_END_SELECTION_Cat3_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon800_alladded_STD_END_SELECTION_Cat4_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon800_alladded_STD_END_SELECTION_Cat4_alladded_Yield_NOUNCERTBUTSTAT.dat

# Sgluon 1000 

./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon1000_alladded_STD_END_SELECTION_Cat0_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon1000_alladded_STD_END_SELECTION_Cat0_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon1000_alladded_STD_END_SELECTION_Cat1_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon1000_alladded_STD_END_SELECTION_Cat1_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon1000_alladded_STD_END_SELECTION_Cat2_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon1000_alladded_STD_END_SELECTION_Cat2_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon1000_alladded_STD_END_SELECTION_Cat3_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon1000_alladded_STD_END_SELECTION_Cat3_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon1000_alladded_STD_END_SELECTION_Cat4_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon1000_alladded_STD_END_SELECTION_Cat4_alladded_Yield_NOUNCERTBUTSTAT.dat

# Sgluon 1250 

./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon1250_alladded_STD_END_SELECTION_Cat0_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon1250_alladded_STD_END_SELECTION_Cat0_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon1250_alladded_STD_END_SELECTION_Cat1_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon1250_alladded_STD_END_SELECTION_Cat1_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon1250_alladded_STD_END_SELECTION_Cat2_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon1250_alladded_STD_END_SELECTION_Cat2_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon1250_alladded_STD_END_SELECTION_Cat3_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon1250_alladded_STD_END_SELECTION_Cat3_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_Sgluon1250_alladded_STD_END_SELECTION_Cat4_alladded_Yield.dat > Files_10April2014/DAT/CH_Sgluon1250_alladded_STD_END_SELECTION_Cat4_alladded_Yield_NOUNCERTBUTSTAT.dat

# RPP 600

./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_UED-RPP-600_alladded_STD_END_SELECTION_Cat0_alladded_Yield.dat > Files_10April2014/DAT/CH_UED-RPP-600_alladded_STD_END_SELECTION_Cat0_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_UED-RPP-600_alladded_STD_END_SELECTION_Cat1_alladded_Yield.dat > Files_10April2014/DAT/CH_UED-RPP-600_alladded_STD_END_SELECTION_Cat1_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_UED-RPP-600_alladded_STD_END_SELECTION_Cat2_alladded_Yield.dat > Files_10April2014/DAT/CH_UED-RPP-600_alladded_STD_END_SELECTION_Cat2_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_UED-RPP-600_alladded_STD_END_SELECTION_Cat3_alladded_Yield.dat > Files_10April2014/DAT/CH_UED-RPP-600_alladded_STD_END_SELECTION_Cat3_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_UED-RPP-600_alladded_STD_END_SELECTION_Cat4_alladded_Yield.dat > Files_10April2014/DAT/CH_UED-RPP-600_alladded_STD_END_SELECTION_Cat4_alladded_Yield_NOUNCERTBUTSTAT.dat

# RPP 800

./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_UED-RPP-800_alladded_STD_END_SELECTION_Cat0_alladded_Yield.dat > Files_10April2014/DAT/CH_UED-RPP-800_alladded_STD_END_SELECTION_Cat0_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_UED-RPP-800_alladded_STD_END_SELECTION_Cat1_alladded_Yield.dat > Files_10April2014/DAT/CH_UED-RPP-800_alladded_STD_END_SELECTION_Cat1_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_UED-RPP-800_alladded_STD_END_SELECTION_Cat2_alladded_Yield.dat > Files_10April2014/DAT/CH_UED-RPP-800_alladded_STD_END_SELECTION_Cat2_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_UED-RPP-800_alladded_STD_END_SELECTION_Cat3_alladded_Yield.dat > Files_10April2014/DAT/CH_UED-RPP-800_alladded_STD_END_SELECTION_Cat3_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_UED-RPP-800_alladded_STD_END_SELECTION_Cat4_alladded_Yield.dat > Files_10April2014/DAT/CH_UED-RPP-800_alladded_STD_END_SELECTION_Cat4_alladded_Yield_NOUNCERTBUTSTAT.dat

# RPP 1000

./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_UED-RPP-1000_alladded_STD_END_SELECTION_Cat0_alladded_Yield.dat > Files_10April2014/DAT/CH_UED-RPP-1000_alladded_STD_END_SELECTION_Cat0_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_UED-RPP-1000_alladded_STD_END_SELECTION_Cat1_alladded_Yield.dat > Files_10April2014/DAT/CH_UED-RPP-1000_alladded_STD_END_SELECTION_Cat1_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_UED-RPP-1000_alladded_STD_END_SELECTION_Cat2_alladded_Yield.dat > Files_10April2014/DAT/CH_UED-RPP-1000_alladded_STD_END_SELECTION_Cat2_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_UED-RPP-1000_alladded_STD_END_SELECTION_Cat3_alladded_Yield.dat > Files_10April2014/DAT/CH_UED-RPP-1000_alladded_STD_END_SELECTION_Cat3_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_UED-RPP-1000_alladded_STD_END_SELECTION_Cat4_alladded_Yield.dat > Files_10April2014/DAT/CH_UED-RPP-1000_alladded_STD_END_SELECTION_Cat4_alladded_Yield_NOUNCERTBUTSTAT.dat

# RPP 1200

./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_UED-RPP-1200_alladded_STD_END_SELECTION_Cat0_alladded_Yield.dat > Files_10April2014/DAT/CH_UED-RPP-1200_alladded_STD_END_SELECTION_Cat0_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_UED-RPP-1200_alladded_STD_END_SELECTION_Cat1_alladded_Yield.dat > Files_10April2014/DAT/CH_UED-RPP-1200_alladded_STD_END_SELECTION_Cat1_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_UED-RPP-1200_alladded_STD_END_SELECTION_Cat2_alladded_Yield.dat > Files_10April2014/DAT/CH_UED-RPP-1200_alladded_STD_END_SELECTION_Cat2_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_UED-RPP-1200_alladded_STD_END_SELECTION_Cat3_alladded_Yield.dat > Files_10April2014/DAT/CH_UED-RPP-1200_alladded_STD_END_SELECTION_Cat3_alladded_Yield_NOUNCERTBUTSTAT.dat
./RemoveUncertaintiesExceptStat.awk Files_10April2014/DAT/CH_UED-RPP-1200_alladded_STD_END_SELECTION_Cat4_alladded_Yield.dat > Files_10April2014/DAT/CH_UED-RPP-1200_alladded_STD_END_SELECTION_Cat4_alladded_Yield_NOUNCERTBUTSTAT.dat
